Fail browser tests if detecting JS or network error within browser (#3875)
This PR adds a listener to browser JS and network errors. At the end of the test, if the listener detected any errors - it will fail the test providing all caught errors. This is important for e2e tests where we some issues might not be reflected in screenshots or by our normal DOM checks. For example this PR helped to uncover three different issues:

1. Error in QuestionEditView/preview.ts where for "static text" questions we hide "question help text" field. But the element is still present in the DOM and preview.ts thinks that it normal visible element and processes it, causing JS error (example from the detector):


```
Detected 1 unhandled JS exceptions in browser during test run:

Page: http://civiform:9000/admin/questions/new?type=static&redirectUrl=%2Fadmin%2Fquestions
Error: TypeError: Cannot set properties of null (setting 'innerHTML')
  at PreviewController.setTextAndHighlightEnumeratorReferences (http:/civiform:9000/assets/javascripts/4f08e7e0dbbabbed9b34e26f3425033f-preview.js:155:30)
  at PreviewController.updateFromNewQuestionHelpText (http:/civiform:9000/assets/javascripts/4f08e7e0dbbabbed9b34e26f3425033f-preview.js:129:27)
  at new PreviewController (http:/civiform:9000/assets/javascripts/4f08e7e0dbbabbed9b34e26f3425033f-preview.js:16:31)
  at http:/civiform:9000/assets/javascripts/4f08e7e0dbbabbed9b34e26f3425033f-preview.js:308:25
  at BrowserErrorWatcher.failIfContainsErrors (src/support/browser_error_watcher.ts:22:11)
  at resetContext (src/support/index.ts:191:31)
  at Object.<anonymous> (src/support/index.ts:235:11)
```

This error is being fixed in this PR.

2. We have overlapping clickable elements. To prevent click on the inner element triggering the listener on the outer element - we use Event.preventDefault. But we haven't added that logic for buttons with form attributes. This causing transient failing GET requests:
image

3. Detected that we use Google Analytics even in browser tests which lead to realizing that we we shouldn't have default analytics id set: Remove default hardcoded google analytics id and allow it to be empty #3876

4. Detected JS error in JS error on applicant file upload page #3896

Lastly fixes linter invocation in formatter/fmt script to pass list of files to lint. Currently it's not linting at all.